module.exports = {
  "Healthcare": {
    "Diagnostics & Research": "🔬⚗️",
    "Biotechnology": "🧬💉",
    "Drug Manufacturers—General": "💊🏭",
    "Medical Distribution": "🚑📦",
    "Medical Devices": "🔬🛠️",
    "Drug Manufacturers—Specialty & Generic": "💊🔬",
    "Health Information Services": "💡🏥",
    "Medical Care Facilities": "🏥💉",
    "Medical Instruments & Supplies": "🔬📦",
    "Healthcare Plans": "💡💉",
    "Pharmaceutical Retailers": "💊🛍️"
  },
  "Basic Materials": {
    "Aluminum": "⛏️🍽️",
    "Steel": "⛏️🔩",
    "Gold": "⛏️💰",
    "Silver": "⛏️🥈",
    "Specialty Chemicals": "⚗️💥",
    "Coking Coal": "⛏️🔥",
    "Chemicals": "⚗️🧪",
    "Agricultural Inputs": "🌾🚜",
    "Building Materials": "🧱🏗️",
    "Other Industrial Metals & Mining": "⛏️🔩",
    "Other Precious Metals & Mining": "⛏️💎",
    "Paper & Paper Products": "🌳📄",
    "Copper": "⛏️🔌",
    "Lumber & Wood Production": "🌳🪓",
    "Independent Oil & Gas": "⛽🌍"
  },
  "Financial Services": {
    "Shell Companies": "💼🐚",
    "Insurance—Life": "💼💖",
    "Asset Management": "💼💰",
    "Banks—Regional": "💼🌍",
    "Insurance—Diversified": "💼🔀",
    "Insurance—Specialty": "💼🌟",
    "Insurance—Property & Casualty": "💼🏠",
    "Capital Markets": "💼💹",
    "Credit Services": "💼💳",
    "Insurance Brokers": "💼🤝",
    "Banks—Diversified": "💼🏦",
    "Financial Data & Stock Exchanges": "💼💹",
    "Mortgage Finance": "💼🏠",
    "Insurance—Reinsurance": "💼🔄",
    "Financial Conglomerates": "💼🏦"
  },
  "Consumer Defensive": {
    "Education & Training Services": "📚💡",
    "Beverages—Brewers": "🍺🏭",
    "Grocery Stores": "🛒🥕",
    "Farm Products": "🌾🚜",
    "Food Distribution": "🍔🚚",
    "Packaged Foods": "🍔📦",
    "Discount Stores": "🛍️💸",
    "Beverages—Non-Alcoholic": "🥤🏭",
    "Household & Personal Products": "🧹🧴",
    "Tobacco": "🚬🏭",
    "Beverages—Wineries & Distilleries": "🍷🏭",
    "Confectioners": "🍬🏭"
  },
  "undefined": { "undefined": "❓" },
  "Real Estate": {
    "REIT—Mortgage": "🏦🏠",
    "REIT—Diversified": "🏢🔄",
    "REIT—Retail": "🏢🛍️",
    "Real Estate—Development": "🏗️🏢",
    "REIT—Specialty": "🏢🌟",
    "REIT—Hotel & Motel": "🏢🛏️",
    "REIT—Residential": "🏢🏠",
    "Real Estate Services": "🏠🤝",
    "REIT—Office": "🏢💼",
    "Real Estate—Diversified": "🏠🔄",
    "REIT—Healthcare Facilities": "🏢🏥",
    "REIT—Industrial": "🏢🏭"
  },
  "Industrials": {
    "Airlines": "✈️🏭",
    "Rental & Leasing Services": "🚗💼",
    "Building Products & Equipment": "🏗️🔨",
    "Airports & Air Services": "✈️🏢",
    "Electrical Equipment & Parts": "🔌🔩",
    "Specialty Business Services": "💼🌟",
    "Engineering & Construction": "👷🏗️",
    "Business Equipment & Supplies": "💼📦",
    "Aerospace & Defense": "🚀🛡️",
    "Pollution & Treatment Controls": "🏭🌍",
    "Staffing & Employment Services": "💼👥",
    "Security & Protection Services": "🔒💼",
    "Farm & Heavy Construction Machinery": "🚜🏗️",
    "Specialty Industrial Machinery": "🏭🌟",
    "Integrated Freight & Logistics": "🚚🔄",
    "Industrial Distribution": "🏭📦",
    "Conglomerates": "🏭🔄",
    "Metal Fabrication": "⚙️🏭",
    "Waste Management": "🗑️🔄",
    "Trucking": "🚚🏭",
    "Marine Shipping": "🚢🏭",
    "Consulting Services": "💼🤝",
    "Railroads": "🚂🛤️",
    "Tools & Accessories": "🔨🔧",
    "Infrastructure Operations": "🏗️🔄"
  },
  "Technology": {
    "Communication Equipment": "📞🔧",
    "Consumer Electronics": "📱📺",
    "Scientific & Technical Instruments": "🔬⚙️",
    "Software—Application": "💻📱",
    "Software—Infrastructure": "💻🌐",
    "Semiconductor Equipment & Materials": "💻🔬",
    "Information Technology Services": "💻🔧",
    "Semiconductors": "💻🔌",
    "Electronics & Computer Distribution": "💻📦",
    "Computer Hardware": "💻🔩",
    "Electronic Components": "🔌🔩",
    "Solar": "☀️🔋"
  },
  "Consumer Cyclical": {
    "Specialty Retail": "🛍️🌟",
    "Auto & Truck Dealerships": "🚗🚛",
    "Travel Services": "✈️🛄",
    "Gambling": "🎰💰",
    "Auto Parts": "🚗🔧",
    "Apparel Retail": "👗🛍️",
    "Textile Manufacturing": "👗🏭",
    "Internet Retail": "🛍️💻",
    "Packaging & Containers": "📦🔩",
    "Furnishings, Fixtures & Appliances": "🛋️🛠️",
    "Leisure": "🏖️🌴",
    "Restaurants": "🍔🍴",
    "Footwear & Accessories": "👠👜",
    "Home Improvement Retail": "🏠🛠️",
    "Auto Manufacturers": "🚗🏭",
    "Lodging": "🛏️🏨",
    "Resorts & Casinos": "🎰🏨",
    "Recreational Vehicles": "🚐🏞️",
    "Personal Services": "💅💇",
    "Luxury Goods": "💍👜",
    "Residential Construction": "🏠🏗️",
    "Department Stores": "🛍️🏬",
    "Apparel Manufacturing": "👗🏭"
  },
  "Energy": {
    "Oil & Gas Equipment & Services": "⛽🔧",
    "Oil & Gas E&P": "⛽🔎",
    "Oil & Gas Midstream": "⛽🔄",
    "Oil & Gas Refining & Marketing": "⛽🏭",
    "Thermal Coal": "⛏️🔥",
    "Oil & Gas Drilling": "⛽🔩",
    "Oil & Gas Integrated": "⛽🔄",
    "Uranium": "☢️⛏️"
  },
  "Communication Services": {
    "Entertainment": "🎥🎵",
    "Advertising Agencies": "📺💼",
    "Telecom Services": "📞🌐",
    "Internet Content & Information": "💻📚",
    "Electronic Gaming & Multimedia": "🎮📺",
    "Broadcasting": "🎥📡",
    "Publishing": "📚🖨️"
  },
  "Utilities": {
    "Utilities—Renewable": "♻️💡",
    "Utilities—Regulated Electric": "⚡💼",
    "Utilities—Diversified": "💡💧",
    "Utilities—Regulated Water": "💧💼",
    "Utilities—Regulated Gas": "⛽💼",
    "Utilities—Independent Power Producers": "⚡🔄"
  },
  "": { "": "❓" },
  "Services": {    "CATV Systems": "📺🔌"
  },
  "Financial": { "Closed-End Fund - Equity": "💼💰" }
}






